# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    docker build -t tomjoypala/nginxfrontend . -f Dockerfile
  displayName: 'Build container image'
- script: |
    docker run tomjoypala/nginxfrontend
  displayName: 'Run container image'
- script: |
    docker ps
  displayName: 'showing running containers'
